apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: secret-controller
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vaultproject.io/policies: "default,secret-controller"
            vaultproject.io/ttl: "24h"
        spec:
          containers:
          - name: secret-controller
            image: "prasadg193/secret-controller:1.0.0"
            imagePullPolicy: Always
            env:
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            args:
            - "-namespace=$(POD_NAMESPACE)"
            - "-vault-addr=http://vault:8200"
            - "-name=$(POD_NAME)"
            - "-cert-threshold=1" # cert renewal threshold in mins
          restartPolicy: OnFailure
