apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: server
        service: server
      annotations:
        vaultproject.io/policies: "default,server"
        vaultproject.io/ttl: "24h"
    spec:
      containers:
        - name: server
          image: "prasadg193/vault-example:server"
          imagePullPolicy: Always
          volumeMounts:
            - name: vault-token
              mountPath: "/var/run/secrets/vaultproject.io"
      initContainers:
        - name: vault-init
          image: "prasadg193/vault-init:1.0.0"
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VAULT_ADDR
              value: 'http://vault.vault-controller.svc.cluster.local:8200'
            - name: VAULT_CONTROLLER_ADDR
              value: 'http://vault-controller.vault-controller.svc.cluster.local'
          args:
            - "-name=$(POD_NAME)"
            - "-namespace=$(POD_NAMESPACE)"
            - "-service-name=server"
            - "-retry-timeout=1" # token/certs request timeout in minutes
          volumeMounts:
            - name: vault-token
              mountPath: "/var/run/secrets/vaultproject.io"
      volumes:
        - name: vault-token
          emptyDir: {}
